# Generated by Django 4.0.3 on 2022-05-07 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='razon_social',
            new_name='marca',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='categoria',
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=2)),
                ('imagen', models.ImageField(upload_to='')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.proveedor')),
            ],
        ),
    ]
