# Generated by Django 4.0.3 on 2022-05-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_rename_razon_social_proveedor_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('U', 'Unisex')], default='hombre', max_length=6),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(choices=[('blanco', 'blanco'), ('negro', 'negro'), ('gris', 'gris')], default='blanco', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='small', max_length=2),
        ),
    ]
