# Generated by Django 4.0.3 on 2022-05-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_producto_categoria_alter_producto_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_de_producto',
            field=models.CharField(choices=[('polera', 'polera'), ('poleron', 'poleron'), ('chaqueta', 'chaqueta')], default='polera', max_length=15, verbose_name='tipo de producto'),
        ),
    ]
