# Generated by Django 4.0.3 on 2022-05-10 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
    ]
